### ISSUE TITLE
Request for listing badges and projectz

### ISSUE THREAD

**Issue by balupton** [badges/awesome-badges#14]
https://github.com/bevry/badges for html rendering and https://github.com/bevry/projectz for readme injection

been around for quite some time: https://github.com/bevry/badges/blob/master/HISTORY.md#v100-2015-september-16

**Comment by calebcartwright** [comment]
Would you like to submit a pull request adding these to the readme?

**Comment by calebcartwright** [comment]
Feel free to send a PR adding them, but I see no need to keep the issue open so going to close
